// import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body><header className='bg-red-700'>
        <p>header</p>
        </header>
        {children}
        <footer 
        style={{
          backgroundColor:"pink",padding:"1rem",
        }}>
          footer
        </footer>
        </body>
        {/* <nav>
          <ul>
            <li>
            <Link href="/profile">PROFILE</Link>
              </li>
              <li>
              <Link href="/blog">BLOG</Link>
              
              
              <Link href="/products">products</Link></li></ul></nav></header>{children}</body> */}
    </html>
  )
}
