import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
// import Link from 'next/link';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "hello 👋👋",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
    <body><header className='bg-white '>
      <p>header</p>
      </header>
      {children}
       <footer 
      style={{
        backgroundColor:"white",padding:"1rem",
      }}>
        footer
      </footer> 
{/*       
       <nav>
        <ul>
          <li>
          <Link href="/profile">PROFILE</Link>
            </li>
            <li>
            <Link href="/blog">BLOG</Link>
            
            
            <Link href="/products">products</Link></li></ul></nav>{children}</body>  */}
            </body>
  </html>
  );
}
