import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body><header>
        <nav>
          <ul>
            <li>
            
              <nav><li>
              <Link href="/blog/first">BLOG1</Link></li>
              <li>
              <Link href="/blog/second">BLOG2</Link>
              </li></nav>
             
              </li></ul></nav></header>{children}</body>
    </html>
  )
}
